# logger_name
# logger_level
# logger_file
logger:
  name: python_api
  level: WARNING
  file: log_my.txt

excel:
  file: cases.xlsx
  sheet: login

database:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: ''
  charset: 'utf8'
  database: 'test'
